version = 0.1
[default.deploy.parameters]
stack_name = "LambdaGatewaySAM1"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
resolve_s3 = true
s3_prefix = "APIGatewaySAM3"
image_repositories = []
