const constantValues = {
  years: [
    { value: 2014, label: 2014 },
    { value: 2015, label: 2015 },
    { value: 2016, label: 2016 },
    { value: 2017, label: 2017 },
    { value: 2018, label: 2018 },
    { value: 2019, label: 2019 },
    { value: 2020, label: 2020 },
    { value: 2021, label: 2021 },
    { value: 2022, label: 2022 },
    { value: 2023, label: 2023 },
    { value: 2024, label: 2024 },
    { value: 2025, label: 2025 },
    { value: 2026, label: 2026 },
    { value: 2027, label: 2027 },
    { value: 2028, label: 2028 },
    { value: 2029, label: 2029 },
  ],
  semesters: [
    { value: 1, label: "1" },
    { value: 2, label: "2" },
    { value: 3, label: "Verão" },
  ],
  days: [
    { value: "SEG", label: "Segunda" },
    { value: "TER", label: "Terça" },
    { value: "QUA", label: "Quarta" },
    { value: "QUI", label: "Quinta" },
    { value: "SEX", label: "Sexta" },
  ],
  hours: [
    { hora: 7, turno: "Manhã" },
    { hora: 8, turno: "Manhã" },
    { hora: 9, turno: "Manhã" },
    { hora: 10, turno: "Manhã" },
    { hora: 11, turno: "Manhã" },
    { hora: 12, turno: "Tarde" },
    { hora: 13, turno: "Tarde" },
    { hora: 14, turno: "Tarde" },
    { hora: 15, turno: "Tarde" },
    { hora: 16, turno: "Tarde" },
    { hora: 17, turno: "Tarde" },
    { hora: 18, turno: "Noite" },
    { hora: 19, turno: "Noite" },
    { hora: 20, turno: "Noite" },
    { hora: 21, turno: "Noite" },
  ],
  hoursTang: [
    { hora: 8, turno: "Manhã" },
    { hora: 10, turno: "Manhã" },
    { hora: 14, turno: "Tarde" },
    { hora: 16, turno: "Tarde" },
    { hora: 18, turno: "Noite" },
    { hora: 20, turno: "Noite" },
  ],
  expectedSemester: [
    { value: 0, label: "0" },
    { value: 1, label: "1" },
    { value: 2, label: "2" },
    { value: 3, label: "3" },
    { value: 4, label: "4" },
    { value: 5, label: "5" },
    { value: 6, label: "6" },
    { value: 7, label: "7" },
    { value: 8, label: "8" },
    { value: 9, label: "9" },
    { value: 10, label: "10" },
    { value: 11, label: "Eletiva Optativa" },
    { value: 12, label: "Eletiva Livre" },
    { value: 12, label: "Não pertence ao curso" },
  ],
  durations: [
    { value: 0, label: "sem aula" },
    { value: 1, label: "1 hora" },
    { value: 2, label: "2 horas" },
    { value: 3, label: "3 horas" },
    { value: 4, label: "4 horas" },
    { value: 5, label: "5 horas" },
    // { value: 6, label: "6 hora" },
  ],
};

export default constantValues;
