INSERT INTO professores (id, laboratorio, curso, apelido, nome) VALUES
  (1, 'LCMAT', 'CC', 'Rivera', 'Luis Antonio Rivera Escriba'),
  (2, 'LCMAT', 'CC', 'Annabell', 'Annabell Del Real Tamariz'),
  (3, 'LCMAT', 'CC', 'Tang', 'Fermín Alfredo Tang Montané'),
  (4, 'LCMAT', 'CC', 'Ausberto', 'Ausberto Silverio Castro Vera'),
  (5, 'LCMAT', 'CC', 'Luis Mariano', 'Luis Mariano del Val Cura'),
  (6, 'LCMAT', 'CC', 'João Luiz', 'João Luiz de Almeida Filho'),
  (7, 'LCMAT', 'Lic Mat', 'Elba', 'Elba Orocia Bravo Asenjo'),
  (8, 'LCMAT', 'Lic Mat', 'Oscar', 'Oscar Alfredo Paz La Torre'),
  (9, 'LCMAT', 'Lic Mat', 'Rigoberto', 'Rigoberto Gregorio Sanabria Castro'),
  (10, 'LCMAT', 'Lic Mat', 'Guillermo', 'Luis Humberto Guillermo Felipe'),
  (11, 'LCMAT', 'Lic Mat', 'Nelson', 'Nelson Machado Barbosa'),
  (12, 'LCMAT', 'Lic Mat', 'Wilma', 'Wilma Dora Huacasi Mamani'),
  (13, 'LCMAT', 'Lic Mat', 'Paulo Beggio', 'Paulo Cesar Beggio'),
  (14, 'LCMAT', 'Lic Mat', 'Paulo Dias', 'Paulo Sérgio Dias da Silva'),
  (15, 'LCMAT', 'Lic Mat', 'Nilson', 'Nilson Sergio Peres Stahl'),
  (16, 'LCMAT', 'Lic Mat', 'Ana Senna', 'Ana Silva de Senna'),
  (17, 'LCFIS', 'Lic Fis', 'Max', 'Max Erik Soffner'),
  (18, 'LCFIS', 'Lic Fis', 'Marcelo Gomes', 'Marcelo Gomes da Silva'),
  (19, 'LCFIS', 'Lic Fis', 'Marcenilda', 'Marcenilda Amorim Lima'),
  (20, 'LCFIS', 'Lic Fis', 'José Augusto', 'José Augusto Pedro Lima'),
  (21, 'LCFIS', 'Lic Fis', 'Leonardo Mota', 'Leonardo Mota de Oliveira'),
  (22, 'LCFIS', 'Lic Fis', 'Roberto Franco', 'Roberto Weider de Assis Franco'),
  (23, 'LCFIS', 'Lic Fis', 'Delson', 'Delson Ubiratan da Silva Schramm'),
  (24, 'LCFIS', 'Lic Fis', 'Marcelo Shoey', 'Marcelo Shoey de Oliveira Massunaga'),
  (25, 'CCH', 'Outro', 'Carlos Alberto', 'Carlos Alberto Manso Lopez'),
  (26, 'CCH', 'Outro', 'Edson', 'Edson Terra Azevedo Filho'),
  (27, 'CCH', 'Outro', 'Pedro Paulo', 'Pedro Paulo Pinto Maia Filho'),
  (28, 'LEPROD', 'Outro', 'Arica', 'José Ramón Arica Chavez'),
  (29, 'LEPROD', 'Outro', 'Molina', 'Manuel Antonio Molina Palma'),
  (30, 'LCMAT', 'CC', 'Bolsista CC 1', 'Bolsista LCMAT CC'),
  (31, 'LCMAT', 'CC', 'Bolsista CC 2', 'Bolsista LCMAT CC'),
  (32, 'LCMAT', 'CC', 'Bolsista CC 3', 'Bolsista LCMAT CC'),
  (33, 'LCMAT', 'Outro', 'Bolsista LCMAT 1', 'Bolsista LCMAT'),
  (34, 'LCMAT', 'Outro', 'Bolsista LCMAT 2', 'Bolsista LCMAT'),
  (35, 'LCMAT', 'Outro', 'Bolsista LCMAT 3', 'Bolsista LCMAT'),
  (36, 'LCFIS', 'Outro', 'Bolsista LCFIS 1', 'Bolsista LCFIS'),
  (37, 'LCFIS', 'Outro', 'Bolsista LCFIS 2', 'Bolsista LCFIS'),
  (38, 'LCFIS', 'Outro', 'Bolsista LCFIS 3', 'Bolsista LCFIS'),
  (39, 'LEPROD', 'Outro', 'Bolsista LEPROD 1', 'Bolsista LEPROD'),
  (40, 'LEPROD', 'Outro', 'Bolsista LEPROD 2', 'Bolsista LEPROD'),
  (41, 'LEPROD', 'Outro', 'Bolsista LEPROD 3', 'Bolsista LEPROD'),
  (42, 'CCH', 'Outro', 'Bolsista CCH 1', 'Bolsista CCH'),
  (43, 'CCH', 'Outro', 'Bolsista CCH 2', 'Bolsista CCH'),
  (44, 'CCH', 'Outro', 'Bolsista CCH 3', 'Bolsista CCH'),
  (45, 'LCMAT', 'Lic Mat', 'Bolsista - Bruna', 'Bruna'),
  (46, 'LCMAT', 'Lic Mat', 'Bolsista - Niander', 'Niander Aguiar Cerqueira'),
  (47, 'LCMAT', 'Lic Mat', 'Bolsista - Rebeca', 'Rebeca'),
  (48, 'LCMAT', 'CC', 'Bolsista - Sânya', 'Sânya Carvalho dos Santos'),
  (49, 'LCMAT', 'CC', 'Bolsista - André', 'André'),
  (50, 'LCMAT', 'CC', 'Bolsista - Eduardo', 'Eduardo'),
  (51, 'LCMAT', 'CC', 'Bolsista - Átila', 'Átila Carvalho Junior');