AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "OurClass>SAM>General>"

Resources:
  # LAYERS
  dbFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dbFunctionSAM
      Description: connect to db
      ContentUri: ./layers/dbConnection
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs16.x
        - nodejs18.x
  # THOSE LAYERS SHOULD BE USED IN THE FUTURE INSTEAD OF A SINGLE LAYER?
  # auxFunctionLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: auxFunctionsSAM
  #     Description: getPayload
  #     ContentUri: ./layers/auxFunctions
  #     CompatibleRuntimes:
  #       - nodejs14.x
  #       - nodejs16.x
  #       - nodejs18.x
  # defaultCRUDFunctionLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: defaultCRUDSAM
  #     Description: default CRUD functions
  #     ContentUri: ./layers/defaultCRUD
  #     CompatibleRuntimes:
  #       - nodejs14.x
  #       - nodejs16.x
  #       - nodejs18.x

  # API GATEWAY
  TimetablingAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: timetablingStage
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # LAMBDA FUNCTIONS
  createProfessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createProfessor
      CodeUri: ./lambdas/professor/createProfessor
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /professor
            Method: post
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  readProfessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: readProfessor
      CodeUri: ./lambdas/professor/readProfessor
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /professor
            Method: get
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  updateProfessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateProfessor
      CodeUri: ./lambdas/professor/updateProfessor
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /professor
            Method: put
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  deleteProfessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deleteProfessor
      CodeUri: ./lambdas/professor/deleteProfessor
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /professor/{id}
            Method: delete
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  createSubject:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createSubject
      CodeUri: ./lambdas/subject/createSubject
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /subject
            Method: post
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  readSubject:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: readSubject
      CodeUri: ./lambdas/subject/readSubject
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /subject
            Method: get
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  updateSubject:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateSubject
      CodeUri: ./lambdas/subject/updateSubject
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /subject
            Method: put
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  deleteSubject:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deleteSubject
      CodeUri: ./lambdas/subject/deleteSubject
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /subject/{id}
            Method: delete
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  createStudent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createStudent
      CodeUri: ./lambdas/student/createStudent
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /student
            Method: post
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  readStudent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: readStudent
      CodeUri: ./lambdas/student/readStudent
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /student
            Method: get
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  updateStudent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateStudent
      CodeUri: ./lambdas/student/updateStudent
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /student
            Method: put
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  deleteStudent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deleteStudent
      CodeUri: ./lambdas/student/deleteStudent
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /student/{id}
            Method: delete
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  createRoom:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createRoom
      CodeUri: ./lambdas/room/createRoom
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /room
            Method: post
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  readRoom:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: readRoom
      CodeUri: ./lambdas/room/readRoom
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /room
            Method: get
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  updateRoom:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateRoom
      CodeUri: ./lambdas/room/updateRoom
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /room
            Method: put
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  deleteRoom:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deleteRoom
      CodeUri: ./lambdas/room/deleteRoom
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /room/{id}
            Method: delete
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  createClassData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createClassData
      CodeUri: ./lambdas/classData/createClassData
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /classData
            Method: post
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  readClassData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: readClassData
      CodeUri: ./lambdas/classData/readClassData
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /classData
            Method: get
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  updateClassData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateClassData
      CodeUri: ./lambdas/classData/updateClassData
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /classData
            Method: put
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  deleteClassData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deleteClassData
      CodeUri: ./lambdas/classData/deleteClassData
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /classData/{id}
            Method: delete
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  createClassTime:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createClassTime
      CodeUri: ./lambdas/classTime/createClassTime
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /classTime
            Method: post
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  readClassTime:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: readClassTime
      CodeUri: ./lambdas/classTime/readClassTime
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /classTime
            Method: get
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  updateClassTime:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateClassTime
      CodeUri: ./lambdas/classTime/updateClassTime
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /classTime
            Method: put
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
  deleteClassTime:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deleteClassTime
      CodeUri: ./lambdas/classTime/deleteClassTime
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /classTime/{id}
            Method: delete
            RestApiId: !Ref TimetablingAPI
      Runtime: nodejs14.x
      Handler: index.handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Layers:
        - !Ref dbFunctionLayer
      Environment:
        Variables:
          DB_HOST: ourclassuirds.cgsgwtemx5r8.us-east-2.rds.amazonaws.com
          DB_NAME: OurClassUIRDS
          DB_USER: tang
          DB_PSWD: annabell
