AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "OurClass>SAM>General>"

Resources:
  # LAYERS
  dbFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dbFunctionSAM
      Description: connect to db
      ContentUri: ./layers/dbConnection
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs16.x
        - nodejs18.x
  auxFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: auxFunctionsSAM
      Description: getPayload
      ContentUri: ./layers/auxFunctions
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs16.x
        - nodejs18.x
  # defaultCRUDFunctionLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: defaultCRUDSAM
  #     Description: default CRUD functions
  #     ContentUri: ./layers/defaultCRUD
  #     CompatibleRuntimes:
  #       - nodejs14.x
  #       - nodejs16.x
  #       - nodejs18.x

  # API GATEWAY
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: timetabling
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # LAMBDA FUNCTIONS
  createProfessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createProfessor
      Runtime: nodejs14.x
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Handler: index.handler
      CodeUri: ./lambdas/professor/createProfessor
      Environment:
        Variables:
          SECRET_NAME: timetablingSecrets
      Layers:
        - !Ref dbFunctionLayer
        - !Ref auxFunctionLayer
        # - !Ref defaultCRUDFunctionLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /professor
            Method: post
            RestApiId: !Ref MyApi
  readSubject:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: readSubject
      Runtime: nodejs14.x
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Handler: index.handler
      CodeUri: ./lambdas/subject/readSubject
      Environment:
        Variables:
          SECRET_NAME: timetablingSecrets
      Layers:
        - !Ref dbFunctionLayer
        - !Ref auxFunctionLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /subject
            Method: get
            RestApiId: !Ref MyApi
  readProfessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: readProfessor
      Runtime: nodejs14.x
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Handler: index.handler
      CodeUri: ./lambdas/professor/readProfessor
      Environment:
        Variables:
          SECRET_NAME: timetablingSecrets
      Layers:
        - !Ref dbFunctionLayer
        - !Ref auxFunctionLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /professor
            Method: get
            RestApiId: !Ref MyApi
  readRoom:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: readRoom
      Runtime: nodejs14.x
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Handler: index.handler
      CodeUri: ./lambdas/room/readRoom
      Environment:
        Variables:
          SECRET_NAME: timetablingSecrets
      Layers:
        - !Ref dbFunctionLayer
        - !Ref auxFunctionLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /room
            Method: get
            RestApiId: !Ref MyApi
  readStudent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: readStudent
      Runtime: nodejs14.x
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Handler: index.handler
      CodeUri: ./lambdas/student/readStudent
      Environment:
        Variables:
          SECRET_NAME: timetablingSecrets
      Layers:
        - !Ref dbFunctionLayer
        - !Ref auxFunctionLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /student
            Method: get
            RestApiId: !Ref MyApi
  updateProfessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateProfessor
      Runtime: nodejs14.x
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Handler: index.handler
      CodeUri: ./lambdas/professor/updateProfessor
      Environment:
        Variables:
          SECRET_NAME: timetablingSecrets
      Layers:
        - !Ref dbFunctionLayer
        - !Ref auxFunctionLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /professor
            Method: put
            RestApiId: !Ref MyApi
  deleteProfessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deleteProfessor
      Runtime: nodejs14.x
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      Handler: index.handler
      CodeUri: ./lambdas/professor/deleteProfessor
      Environment:
        Variables:
          SECRET_NAME: timetablingSecrets
      Layers:
        - !Ref dbFunctionLayer
        - !Ref auxFunctionLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /professor/{id}
            Method: delete
            RestApiId: !Ref MyApi
